export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const ADD_TO_BOOKMARK_LIST = 'ADD_TO_BOOKMARK_LIST';
export const REMOVE_FROM_BOOKMARK_LIST = 'REMOVE_FROM_BOOKMARK_LIST';
export const GET_BOOKS_ERROR = 'GET_BOOKS_ERROR';
export const ADD_NOTE = 'ADD_NOTE';
